name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install deps
        run: yarn install

      - name: Build lib
        run: yarn run build

      - name: Check diff
        run: git diff --exit-code HEAD
