name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  package:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest

      - name: Install deps
        run: yarn install

      - name: Clean dist
        run: yarn clean

      - name: Build dist
        run: yarn nx build

      - name: Check diff
        run: git diff --exit-code HEAD

      - name: Generate docs
        run: yarn doc

      - name: Test lib
        run: yarn test
